### ISSUE TITLE
Please add support to display rendered pixlet webp

### ISSUE THREAD

**Issue by GITHUB-139** [tavdog/Tidbyt-hdk-arduino#1]
Ive installed the HDK from tidbyt and have niothing but issues its un reliable in processing / pining uop url and continusully stops and goes blanks and a few fdiffren webp get attempted to display,  Its un fortunate tidbyt people will not allow me to 1 PUSH the webp line you can on the cloud connect ones, 2 cannot set the the ibtervals for the display, I want to control on local server what to pust to the tidbyt display and when,  Ive modified a few of the community apps so they suit my needs but having issues with the hdk generating thens gfx errors randomly  additionally tidbyt people gont want to share their default clock and weather app, which i dont understand why its so hard to remove their api key or simply cange their app to use the Free NWS feed instead that DONT need the bs keys.  That what I want to change in their app or have ti us my openweather api key not theirs.  Anyways if you add support for the pixlet rendered webp that be great.

**Comment by tavdog** [comment]
You can generate gif files with pixlet render by passing the --gif flag

**Comment by GITHUB-139** [comment]
I’ll give that a try will set up a test esp32 to see what happens,  does gif support the marque (scrolling messages) a couple of the community apps i changed the static text fields to maquree and pass the parm in on command line in script for example:


Was not readable repasted code sample in next comment.

**Comment by GITHUB-139** [comment]
````
if [[ ${isec} -eq 0 ]]; then 
date -d "$time + 0 seconds" +"%l:%M %p" | awk '{$1=$1};1' > ${webpath}/tidbyt_02.time

((ran=ran+1))

# ambientweather station
${binpath}/pixlet render ${binpath}/apps/ambient_weather.${fshift}.star "temp_sensor_index=tempSensor1" "humidity_sensor_index=humiditySensor1" "application_key=Removed" "api_key=Removed" "station_id=5xxxxxxxx4" "title=`cat ${webpath}/tidbyt_02.time`" "wcond=`cat ${datapath}/nws.shortForecast.forecast`" -o ${webpath}/tidbyt_02.p1.webp 
RESULT=$?
if [ $RESULT -ge 1 ]; then
if [[ -f ${webpath}/tidbyt_02.p1.webp ]]; then
 rm ${webpath}/tidbyt_02.p1.webp
fi
fi
fi

sleep 1

if [[ $ran -gt 2 ]] && [[ -f ${webpath}/tidbyt_02.p1.webp ]]; then cp ${webpath}/tidbyt_02.p1.webp ${webpath}/display.webp; fi

done
```

Basically the script runs and updates on 00 seconds so the time and weather station data displayed, then at 20 and 40 run 2 other then back main one the timeing is unreliable never know when the page will display, and cannot see in their source how to check to always update screen if new lfile seen as i clearly see in pio devoce monitor they know a file was read with size, maybe they need to correct that as well, anyways  with there base theirs no control when or what displayed and the scrolling message make reliablity worse.  so hopefully yours might work better.

connection to HUB75
![IMG_7658](https://github.com/tavdog/Tidbyt-hdk-arduino/assets/163683839/4e5e2da1-80db-4d2d-a380-776079adc1a1)

**Comment by tavdog** [comment]
Is your goal to a have a local only tidbyt  so that no tidbyt cloud is used for any reason ?  I don't know about the scrolling reliability but pushing webp to the tidbyt cloud is pretty reliable.

**Comment by GITHUB-139** [comment]
Hi Travis, correct I do not want to rely on tidbyt cloud at all, all apps should be ran an hosted locally within my local network.  most items will just be cycled every 15-30 seconds, but its critical for time sensitive even to be displayed immediately, so able to push to would be ideal then we only are dealing with internel network ledency.Send from ***@***.*** Apr 2, 2024, at 2:21 PM, Tavis ***@***.***> wrote:﻿
Is your goal to a have a local only tidbyt  so that no tidbyt cloud is used for any reason ?  I don't know about the scrolling reliability but pushing webp to the tidbyt cloud is pretty reliable.

**Comment by GITHUB-139** [comment]
heres caption of log btw from device monitor when their firemade the screen goes ***@***.***:~/tidbyt/hdk-main# tail -n 20 pio.logE (349656) gfx: Could not draw webpE (349692) gfx: Could not create WebP decoderE (349692) gfx: Could not draw webpE (349729) gfx: Could not create WebP decoderE (349729) gfx: Could not draw webpE (349765) gfx: Could not create WebP decoderE (349766) gfx: Could not draw webpE (349802) gfx: Could not create WebP decoderE (349802) gfx: Could not draw webpE (349837) gfx: Could not create WebP decoderE (349837) gfx: Could not draw webpE (349872) gfx: Could not create WebP decoderE (349872) gfx: Could not draw webpE (349910) gfx: Could not create WebP decoderE (349910) gfx: Could not draw webpE (349948) gfx: Could not create WebP decoderE (349949) gfx: Could not draw webpI (349949) main: Updated webp (110444 bytes)E (350003) gfx: Could not create WebP decoderE (350003) gfx: Could not draw ***@***.***:~/tidbyt/hdk-main# ```Send from ***@***.*** Apr 2, 2024, at 3:19 PM, Robert Montavon ***@***.***> wrote:﻿Hi Travis, correct I do not want to rely on tidbyt cloud at all, all apps should be ran an hosted locally within my local network.  most items will just be cycled every 15-30 seconds, but its critical for time sensitive even to be displayed immediately, so able to push to would be ideal then we only are dealing with internel network ledency.Send from ***@***.*** Apr 2, 2024, at 2:21 PM, Tavis ***@***.***> wrote:﻿
Is your goal to a have a local only tidbyt  so that no tidbyt cloud is used for any reason ?  I don't know about the scrolling reliability but pushing webp to the tidbyt cloud is pretty reliable.
